[package]
name = "nym-sphinx-types"
version = "0.2.0"
description = "Re-export sphinx packet types"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
sphinx-packet = { git = "https://github.com/nymtech/sphinx.git", branch = "simon/x25519", optional = true }
nym-outfox = { path = "../../../nym-outfox", optional = true }
thiserror = { workspace = true }

[features]
default = ["sphinx"]
sphinx = ["sphinx-packet"]
outfox = ["nym-outfox"]
