[package]
name = "nym_compact_ecash"
version = "0.1.0"
authors = ["Ania Piotrowska <ania@nymtech.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
bls12_381 = { git = "https://github.com/jstuczyn/bls12_381.git", branch = "gt-serialisation", default-features = false, features = ["alloc", "pairings", "experimental", "zeroize"]}
itertools = "0.10"
digest = "0.9"
rand = "0.8"
thiserror = "1.0"
sha2 = "0.9"
bs58 = "0.4.0"
rayon = "1.5.0"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[dependencies.ff]
version = "0.11"
default-features = false

[dependencies.group]
version = "0.11"
default-features = false


[[bench]]
name = "benchmarks_group_operations"
path = "benches/benchmarks_group_operations.rs"
harness = false

[[bench]]
name = "benchmarks_expiration_date_signatures"
path = "benches/benchmarks_expiration_date_signatures.rs"
harness = false

[[bench]]
name = "benchmarks_coin_indices_signatures"
path = "benches/benchmarks_coin_indices_signatures.rs"
harness = false

[[bench]]
name = "benchmarks_ecash_e2e"
path = "benches/benchmarks_ecash_e2e.rs"
harness = false