[package]
name = "nym-mixnet-client"
version = "0.1.0"
authors = ["Jedrzej Stuczynski <andrew@nymtech.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
log = { workspace = true }
tokio = { version = "1.24.1", features = ["time", "net", "rt"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
rustls = {version = "0.21.1", features = ["dangerous_configuration", "quic"]}
quinn = "0.10.1"
bytes = "*"

# internal
nym-sphinx = { path = "../../nymsphinx" }
nym-task = { path = "../../task" }
