[package]
name = "contracts-common"
version = "0.1.0"
authors = ["Jędrzej Stuczyński <andrew@nymtech.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.4.0"
cosmwasm-std = "1.0.0-beta8"
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }


blake3 = { version = "1.3.1", features = ["traits-preview"], optional = true }
digest = { version = "0.10.3", optional = true }
generic-array = { version = "0.14.5", features = ["serde"], optional = true }

[features]
committable_trait = ["blake3", "digest", "generic-array"]