[package]
name = "nym-node-requests"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
nym-crypto = { path = "../../common/crypto", features = ["asymmetric"] }

# feature-specific dependencies:

## client:
async-trait = { workspace = true, optional = true }
http-api-client = { path = "../../common/http-api-client", optional = true }

## openapi:
utoipa = { workspace = true, optional = true }
nym-bin-common = { path = "../../common/bin-common" }

[features]
default = ["client"]
client = ["http-api-client", "async-trait"]
openapi = ["utoipa", "nym-bin-common/openapi"]
