[package]
name = "nym-node-requests"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utoipa = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }

nym-bin-common = { path = "../../common/bin-common", optional = true, features = ["openapi"] }
nym-crypto = { path = "../../common/crypto", features = ["asymmetric"] }

[features]
default = ["client"]
client = []
openapi = ["utoipa", "nym-bin-common", "serde_json"]
