[package]
name = "nym_online_divisible_ecash"
version = "0.1.0"
author = ["Ania Piotrowska <ania@nymtech.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = { workspace = true }
bs58 = "0.4.0"
digest = "0.9"
ff = { workspace = true }
group = { workspace = true }
itertools = "0.10"
rand = "0.8"
sha2 = "0.9"
thiserror = "1.0"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
