[package]
name = "socks5-c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bip39 = { version = "2.0.0", features = ["zeroize"] }
dirs = "4.0"
eyre = "0.6.5"
futures = "0.3"
itertools = "0.10.5"
rand = "0.8"
reqwest = { version = "0.11", features = ["json", "socks"] }
rust-embed = { version = "6.4.2", features = ["include-exclude"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
tap = "1.0.1"
# tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next", features = ["clipboard-write-text", "native-tls-vendored", "notification-all", "shell-open"] }
tendermint-rpc = "0.23.0"
thiserror = "1.0"
time = { version = "0.3.17", features = ["local-offset"] }
tokio = { version = "1.24.1", features = ["sync", "time"] }
url = "2.2"
yaml-rust = "0.4"

nym-client-core = { path = "../common/client-core", default-features = false }
nym-api-requests = { path = "../nym-api/nym-api-requests" }
nym-contracts-common = { path = "../common/cosmwasm-smart-contracts/contracts-common"}
nym-config-common = { path = "../common/config", package = "nym-config" }
nym-credential-storage = { path = "../common/credential-storage" }
nym-crypto = { path = "../common/crypto" }
nym-bin-common = { path = "../common/bin-common"}
nym-socks5-client-core = { path = "../common/socks5-client-core", default-features = false }
nym-task = { path = "../common/task" }


[lib]
name = "my_rust_module"
crate-type = ["staticlib"]