[package]
name = "nonexhaustive-delayqueue"
version = "0.1.0"
authors = ["Jędrzej Stuczyński <andrew@nymtech.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = [] }
tokio-stream = "0.1.9" # this one seems to be a thing until `Stream` trait is stabilised in stdlib
tokio-util = { version = "0.7.3", features = ["time"] }

[target."cfg(target_arch = \"wasm32\")".dependencies.wasm-timer]
git = "https://github.com/jstuczyn/wasm-timer"
rev = "2859241251dd00c54a9c99b74727b99bd7feffb4"

[target."cfg(target_arch = \"wasm32\")".dependencies.slab]
version = "0.4.4"

[target."cfg(target_arch = \"wasm32\")".dependencies.futures-core]
version = "0.3.0"