[package]
name = "nym-node"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
bytes = "1.5.0"
hyper = { workspace = true }
mime = "0.3.17"
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.9.25"
thiserror = { workspace = true }
tracing = { workspace = true }
tower = { version = "0.4.13" }
tower-http = { version = "0.4.4", features = ["fs"] }

nym-bin-common = { path = "../common/bin-common" }
