[package]
name = "nym-node"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bytes = "1.5.0"
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.9.25"
thiserror = { workspace = true }
tracing = { workspace = true }

# HTTP API:
axum = { workspace = true }
mime = "0.3.17"
hyper = { workspace = true }
tower = { version = "0.4.13" }
tower-http = { version = "0.4.4", features = ["fs"] }
utoipa = { version = "3.5.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3.1.5", features = ["axum"] }

# if we ever wanted redoc/rapidoc bridges:
#utoipa-redoc = { version = "0.1.0", features = ["axum"] }
#utoipa-rapidoc = { version = "0.1.0", features = ["axum"] }


nym-bin-common = { path = "../common/bin-common" }
