[package]
name = "coconut-dkg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
coconut-dkg-common = { path = "../../common/cosmwasm-smart-contracts/coconut-dkg-contract" }
config = { path = "../../common/config"}

bs58 = "0.4"
cosmwasm-std = { version = "1.0.0-beta8", features = ["staking"] }
cosmwasm-storage = "1.0.0-beta8"
cw-storage-plus = "0.13.2"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
bech32 = "0.9.0"
thiserror = "1.0.23"
