name: Publish Nym binaries

on:
  workflow_dispatch:
    inputs:  
      add_tokio_unstable:
        description: 'True to add RUSTFLAGS="--cfg tokio_unstable"'
        required: true
        default: false
        type: boolean
      release_tag:
        description: 'Release tag to update'
        required: false
        type: string
  release:
    types: [created]
    
env:
  NETWORK: mainnet    

jobs:
  publish-nym:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        if: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag != '' }}"
        with:
          ref: ${{ github.event.inputs.release_tag }}

      - uses: actions/checkout@v3
        if: "${{ github.event.inputs.release_tag == '' }}"

      - run: git log

      - name: Install Dependencies (Linux)
        run: sudo apt-get update && sudo apt-get -y install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libudev-dev squashfs-tools

      - name: Check the release tag starts with `nym-binaries-`
        if: startsWith(github.ref, 'refs/tags/nym-binaries-') == false && github.event_name != 'workflow_dispatch'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Release tag did not start with nym-binaries-...')
            
      - name: Sets env vars for tokio if set in manual dispatch inputs
        run: |
          echo 'RUSTFLAGS="--cfg tokio_unstable"' >> $GITHUB_ENV
        if: github.event_name == 'workflow_dispatch' && inputs.add_tokio_unstable == true

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build all binaries
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            target/release/nym-client
            target/release/nym-gateway
            target/release/nym-mixnode
            target/release/nym-socks5-client
            target/release/nym-validator-api
            target/release/nym-network-requester
            target/release/nym-network-statistics
            target/release/nym-cli
          retention-days: 30

      - uses: AButler/upload-release-assets@v2.0
        with:
          # see https://stackoverflow.com/questions/71045674/how-to-check-if-an-optional-workflow-dispatch-input-is-set-or-not
          if: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag != '' }}"
          files: 'target/release/nym-client;target/release/nym-gateway;target/release/nym-mixnode;target/release/nym-socks5-client;target/release/nym-validator-api;target/release/nym-network-requester;target/release/nym-network-statistics;target/release/nym-cli'
          release-tag: ${{ inputs.release_tag }}

      - name: Upload to release based on tag name
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with:
          files: |
            target/release/nym-client
            target/release/nym-gateway
            target/release/nym-mixnode
            target/release/nym-socks5-client
            target/release/nym-validator-api
            target/release/nym-network-requester
            target/release/nym-network-statistics
            target/release/nym-cli
